### ISSUE TITLE
Setting Master Password -- Missing UI/CLI/API?

### ISSUE THREAD

**Issue by prologic** [thusoy/pwm#1]
There seems to be no UI/API to set a Master Password?

```
$ pwm -h
usage: pwm [-h] [-v] [-c <config-file>] {get,search} ...

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Increase verbosity
  -c <config-file>, --config-file <config-file>
                        Path to config file to use. Default:
                        /Users/s2092651/.pwm/config

Action:
  {get,search}          What do you want to do?
    get                 Get the key for a domain
    search              Search for existing domains
```

**Comment by prologic** [comment]
Wait ... Or have I misunderstood how this works? Does it not matter what Master Password you use at all? Can you use a different Master Password per entry if you wanted to?

**Comment by afflux** [comment]
The idea is to derive the password like this:

```
password = encode(hash(master, domain, salt))
```

Of this, only `(domain, salt)` pairs are stored in a database. This way there is no actual password stored anywhere. The salt (and thus the need to store anything at all) is necessary to introduce non-determinism - e.g. to be able to handle for example site-required password changes (as tends to happen in the event of a compromised website authentication database).

(Your conclusion is correct, there is no requirement for you to use the same master password for each domain. In my opinion, that would defeat the purpose, though.)

**Comment by prologic** [comment]
Gotcha :) Bit of a big misunderstanding there! :)

It started to become more obvious the more I reda your code!

cheers
James

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by thusoy** [comment]
Thanks for filing the issue! I tried to clarify the idea a bit in the readme, but it seems you have steered onto the right track now. :) Let us know if you have any more questions!

**Comment by prologic** [comment]
See my email to you :) Thanks!

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
